"""add personal study data

Revision ID: 0477a61442fe
Revises: 
Create Date: 2026-07-07 13:25:19.602328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0477a61442fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('intention', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_goal_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_goal_user_id'), ['user_id'], unique=False)

    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_user_id'), ['user_id'], unique=False)

    op.create_table('planner_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planner_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planner_event_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planner_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planner_event_user_id'), ['user_id'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_user_id'), ['user_id'], unique=False)

    op.create_table('user_app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_app_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_app_state_user_id'), ['user_id'], unique=True)

    op.create_table('exam_milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_milestone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_milestone_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_milestone_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_subject_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_subject_exam_id'), ['exam_id'], unique=False)

    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('timer_mode', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('study_seconds', sa.Integer(), nullable=False),
    sa.Column('break_seconds', sa.Integer(), nullable=False),
    sa.Column('session_goal', sa.String(length=255), nullable=True),
    sa.Column('goal_result', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_session_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_session_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('repeat_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)

    op.create_table('distraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distraction_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distraction_user_id'), ['user_id'], unique=False)

    op.create_table('exam_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_chapter_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_chapter_exam_subject_id'), ['exam_subject_id'], unique=False)

    op.create_table('exam_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('exam_chapter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exam_chapter_id'], ['exam_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_topic_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_topic_exam_chapter_id'), ['exam_chapter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_topic_exam_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_exam_topic_client_id'))

    op.drop_table('exam_topic')
    with op.batch_alter_table('exam_chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_chapter_exam_subject_id'))
        batch_op.drop_index(batch_op.f('ix_exam_chapter_client_id'))

    op.drop_table('exam_chapter')
    with op.batch_alter_table('distraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distraction_user_id'))
        batch_op.drop_index(batch_op.f('ix_distraction_client_id'))

    op.drop_table('distraction')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_client_id'))

    op.drop_table('task')
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_session_client_id'))

    op.drop_table('study_session')
    with op.batch_alter_table('exam_subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_subject_exam_id'))
        batch_op.drop_index(batch_op.f('ix_exam_subject_client_id'))

    op.drop_table('exam_subject')
    with op.batch_alter_table('exam_milestone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_milestone_exam_id'))
        batch_op.drop_index(batch_op.f('ix_exam_milestone_client_id'))

    op.drop_table('exam_milestone')
    with op.batch_alter_table('user_app_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_app_state_user_id'))

    op.drop_table('user_app_state')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_subject_client_id'))

    op.drop_table('subject')
    with op.batch_alter_table('planner_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planner_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_planner_event_date'))
        batch_op.drop_index(batch_op.f('ix_planner_event_client_id'))

    op.drop_table('planner_event')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_client_id'))

    op.drop_table('exam')
    with op.batch_alter_table('daily_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_goal_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_goal_date'))

    op.drop_table('daily_goal')
    # ### end Alembic commands ###
